const emojiMap: { [key: string]: string } = {
  // Classic Smileys
  ':)': '😊',
  ':-)': '😊',
  ':(': '😞',
  ':-(': '😞',
  ':D': '😄',
  ':-D': '😄',
  ':P': '😜',
  ':-P': '😜',
  ';)': '😉',
  ';-)': '😉',
  ':|': '😐',
  ':-|': '😐',
  ':o': '😮',
  ':-o': '😮',
  'B)': '😎',
  'B-)': '😎',
  '8)': '😎',
  '8-)': '😎',
  ':/': '😕',
  ':-/': '😕',
  ':\\': '😕',
  ':-\\': '😕',
  ':*': '😘',
  ':-*': '😘',
  ':3': '😺',
  XD: '😆',
  ':-O': '😲',
  ':O': '😲',
  ':p': '😜',
  ':-p': '😜',
  ':b': '😋',
  ':-b': '😋',
  '>:)': '😈',
  '>:-)': '😈',
  '>:(': '👿',
  '>:-(': '👿',
  ":'(": '😢',
  ":'-)": '😢',
  ':-x': '😷',
  ':x': '😷',
  ':X': '😷',
  ':-X': '😷',
  ':s': '😖',
  ':-s': '😖',
  ':$': '😳',
  ':-$': '😳',
  ':?': '😕',
  ':-?': '😕',
  ':@': '😡',
  ':-@': '😡',
  'D:': '😧',
  'D;': '😧',
  '>:D': '😆',
  '>:-D': '😆',
  '>;)': '😜',
  '>;-D': '😆',
  '-_-': '😑',
  '>.<': '😣',
  '._.': '😐',
  ':^)': '😊',
  ':-^)': '😊',

  // Hearts and Symbols
  '<3': '❤️',
  '</3': '💔',
  '<\\3': '💔',
  ':heart:': '❤️',
  ':broken_heart:': '💔',
  ':star:': '⭐',
  ':star2:': '🌟',
  ':sparkles:': '✨',
  ':tada:': '🎉',
  ':balloon:': '🎈',
  ':gift:': '🎁',
  ':fire:': '🔥',
  ':boom:': '💥',
  ':zap:': '⚡',
  ':100:': '💯',
  ':rocket:': '🚀',
  ':bulb:': '💡',
  ':exclamation:': '❗',
  ':question:': '❓',

  // Gestures and People
  ':thumbsup:': '👍',
  ':thumbsdown:': '👎',
  ':clap:': '👏',
  ':pray:': '🙏',
  ':wave:': '👋',
  ':ok_hand:': '👌',
  ':muscle:': '💪',
  ':point_right:': '👉',
  ':point_left:': '👈',
  ':point_up:': '👆',
  ':point_down:': '👇',
  ':raised_hands:': '🙌',
  ':fist:': '✊',
  ':crossed_fingers:': '🤞',
  ':victory:': '✌️',
  ':peace:': '✌️',
  ':eyes:': '👀',
  ':facepalm:': '🤦',
  ':shrug:': '🤷',
  ':scream:': '😱',
  ':angry:': '😡',
  ':rage:': '😡',
  ':triumph:': '😤',
  ':cry:': '😢',
  ':sob:': '😭',
  ':laugh:': '😂',
  ':joy:': '😂',
  ':rofl:': '🤣',
  ':blush:': '😊',
  ':grin:': '😁',
  ':relieved:': '😌',
  ':sleepy:': '😪',
  ':dizzy_face:': '😵',
  ':neutral_face:': '😐',
  ':smirk:': '😏',
  ':wink:': '😉',
  ':hug:': '🤗',
  ':mask:': '😷',
  ':nerd:': '🤓',
  ':thinking:': '🤔',
  ':smile:': '🙂',
  ':smiley:': '😃',
  ':grinning:': '😀',
  ':kissing:': '😗',
  ':kissing_heart:': '😘',
  ':kissing_closed_eyes:': '😚',
  ':kissing_smiling_eyes:': '😙',
  ':hugging:': '🤗',
  ':no_mouth:': '😶',
  ':innocent:': '😇',
  ':confused:': '😕',
  ':sweat:': '😅',
  ':sweat_smile:': '😅',
  ':upside_down:': '🙃',
  ':frowning:': '☹️',
  ':slightly_frowning:': '🙁',
  ':open_mouth:': '😮',
  ':hushed:': '😯',
  ':sleeping:': '😴',
  ':relaxed:': '☺️',
  ':yum:': '😋',
  ':stuck_out_tongue:': '😛',
  ':stuck_out_tongue_winking_eye:': '😜',
  ':stuck_out_tongue_closed_eyes:': '😝',
  ':money_mouth:': '🤑',
  ':astonished:': '😲',
  ':worried:': '😟',
  ':pensive:': '😔',
  ':anguished:': '😧',
  ':fearful:': '😨',
  ':cold_sweat:': '😰',
  ':disappointed_relieved:': '😥',
  ':crying:': '😢',
  ':persevere:': '😣',
  ':disappointed:': '😞',
  ':sweat_drops:': '💦',
  ':droplet:': '💧',
  ':dizzy:': '😵',
  ':roll_eyes:': '🙄',
  ':expressionless:': '😑',
  ':grimacing:': '😬',
  ':flushed:': '😳',
  ':zipper_mouth:': '🤐',
  ':thermometer_face:': '🤒',
  ':head_bandage:': '🤕',
  ':nauseated_face:': '🤢',
  ':sneezing_face:': '🤧',
  ':hot_face:': '🥵',
  ':cold_face:': '🥶',
  ':woozy_face:': '🥴',
  ':exploding_head:': '🤯',
  ':cowboy:': '🤠',
  ':clown:': '🤡',
  ':ghost:': '👻',
  ':alien:': '👽',
  ':robot:': '🤖',
  ':skull:': '💀',
  ':skull_crossbones:': '☠️',
  ':poop:': '💩',
  ':jack_o_lantern:': '🎃',
  ':smiling_imp:': '😈',
  ':imp:': '👿',

  // Animals and Nature
  ':dog:': '🐶',
  ':cat:': '🐱',
  ':mouse:': '🐭',
  ':rabbit:': '🐰',
  ':fox:': '🦊',
  ':bear:': '🐻',
  ':panda:': '🐼',
  ':koala:': '🐨',
  ':tiger:': '🐯',
  ':lion:': '🦁',
  ':cow:': '🐮',
  ':pig:': '🐷',
  ':frog:': '🐸',
  ':chicken:': '🐔',
  ':penguin:': '🐧',
  ':bird:': '🐦',
  ':eagle:': '🦅',
  ':duck:': '🦆',
  ':swan:': '🦢',
  ':owl:': '🦉',
  ':bat:': '🦇',
  ':wolf:': '🐺',
  ':horse:': '🐴',
  ':unicorn:': '🦄',
  ':bee:': '🐝',
  ':ladybug:': '🐞',
  ':ant:': '🐜',
  ':butterfly:': '🦋',
  ':fish:': '🐟',
  ':tropical_fish:': '🐠',
  ':dolphin:': '🐬',
  ':whale:': '🐳',
  ':elephant:': '🐘',
  ':crocodile:': '🐊',
  ':turtle:': '🐢',
  ':snake:': '🐍',
  ':lizard:': '🦎',
  ':dragon:': '🐉',
  ':spider:': '🕷️',
  ':scorpion:': '🦂',
  ':crab:': '🦀',
  ':octopus:': '🐙',
  ':lobster:': '🦞',
  ':snail:': '🐌',
  ':shell:': '🐚',
  ':peach:': '🍑',
  ':eggplant:': '🍆',
  ':banana:': '🍌',
  ':watermelon:': '🍉',
  ':apple:': '🍎',
  ':cherries:': '🍒',
  ':pineapple:': '🍍',
  ':strawberry:': '🍓',
  ':kiwi:': '🥝',
  ':grapes:': '🍇',
  ':melon:': '🍈',
  ':lemon:': '🍋',
  ':coconut:': '🥥',
  ':avocado:': '🥑',
  ':broccoli:': '🥦',
  ':tomato:': '🍅',
  ':corn:': '🌽',
  ':carrot:': '🥕',
  ':garlic:': '🧄',
  ':onion:': '🧅',
  ':mushroom:': '🍄',
  ':cactus:': '🌵',
  ':palm_tree:': '🌴',
  ':deciduous_tree:': '🌳',
  ':evergreen_tree:': '🌲',
  ':herb:': '🌿',
  ':maple_leaf:': '🍁',
  ':fallen_leaf:': '🍂',
  ':sunflower:': '🌻',
  ':rose:': '🌹',
  ':tulip:': '🌷',
  ':seedling:': '🌱',
  ':hibiscus:': '🌺',
  ':cherry_blossom:': '🌸',

  // Food and Drink
  ':burger:': '🍔',
  ':fries:': '🍟',
  ':pizza:': '🍕',
  ':hotdog:': '🌭',
  ':taco:': '🌮',
  ':burrito:': '🌯',
  ':sandwich:': '🥪',
  ':spaghetti:': '🍝',
  ':ramen:': '🍜',
  ':sushi:': '🍣',
  ':bento:': '🍱',
  ':curry:': '🍛',
  ':stew:': '🍲',
  ':fish_cake:': '🍥',
  ':ice_cream:': '🍨',
  ':shaved_ice:': '🍧',
  ':cake:': '🍰',
  ':pie:': '🥧',
  ':cupcake:': '🧁',
  ':chocolate_bar:': '🍫',
  ':candy:': '🍬',
  ':lollipop:': '🍭',
  ':doughnut:': '🍩',
  ':cookie:': '🍪',
  ':milk:': '🥛',
  ':coffee:': '☕',
  ':tea:': '🍵',
  ':beverage_box:': '🧃',
  ':bottle:': '🍾',
  ':wine:': '🍷',
  ':cocktail:': '🍸',
  ':beer:': '🍺',
  ':champagne:': '🥂',
  ':sake:': '🍶',
  ':tumbler_glass:': '🥃',
  ':champagne_glass:': '🍸',
  ':tropical_drink:': '🍹',
  ':beer_mug:': '🍻',
  ':popcorn:': '🍿',
  ':fork_and_knife:': '🍴',
  ':spoon:': '🥄',
  ':chopsticks:': '🥢',
  ':salt:': '🧂',
  ':bowl_with_spoon:': '🥣',
  ':takeout_box:': '🥡',

  // Activities and Sports
  ':soccer:': '⚽',
  ':basketball:': '🏀',
  ':football:': '🏈',
  ':baseball:': '⚾',
  ':tennis:': '🎾',
  ':volleyball:': '🏐',
  ':rugby:': '🏉',
  ':golf:': '⛳',
  ':8ball:': '🎱',
  ':ping_pong:': '🏓',
  ':badminton:': '🏸',
  ':hockey:': '🏒',
  ':ice_hockey:': '🏒',
  ':fishing:': '🎣',
  ':bicyclist:': '🚴',
  ':mountain_biking:': '🚵',
  ':swimming:': '🏊',
  ':diving:': '🤿',
  ':weightlifting:': '🏋️',
  ':surfing:': '🏄',
  ':skiing:': '🎿',
  ':snowboarding:': '🏂',
  ':skateboard:': '🛹',
  ':roller_skate:': '🛼',
  ':boomerang:': '🪃',
  ':karate:': '🥋',
  ':boxing:': '🥊',
  ':wrestling:': '🤼',
  ':running:': '🏃',
  ':jogging:': '🏃',
  ':fencing:': '🤺',
  ':archery:': '🏹',
  ':gymnastics:': '🤸',
  ':circus_tent:': '🎪',
  ':goal_net:': '🥅',
  ':kite:': '🪁',
  ':parachute:': '🪂',
  ':yoyo:': '🪀',

  // Travel and Places
  ':car:': '🚗',
  ':taxi:': '🚕',
  ':bus:': '🚌',
  ':trolleybus:': '🚎',
  ':truck:': '🚚',
  ':ambulance:': '🚑',
  ':fire_engine:': '🚒',
  ':police_car:': '🚓',
  ':bicycle:': '🚲',
  ':motor_scooter:': '🛵',
  ':train:': '🚆',
  ':metro:': '🚇',
  ':tram:': '🚊',
  ':light_rail:': '🚈',
  ':station:': '🚉',
  ':airplane:': '✈️',
  ':small_airplane:': '🛩️',
  ':helicopter:': '🚁',
  ':canoe:': '🛶',
  ':sailboat:': '⛵',
  ':ferry:': '⛴️',
  ':cruise_ship:': '🛳️',
  ':ship:': '🚢',
  ':anchor:': '⚓',
  ':speedboat:': '🚤',
  ':mountain_cableway:': '🚠',
  ':tramway:': '🚊',
  ':busstop:': '🚏',
  ':fuelpump:': '⛽',
  ':construction:': '🚧',
  ':traffic_light:': '🚦',
  ':checkered_flag:': '🏁',
  ':motorway:': '🛣️',
  ':railway_track:': '🛤️',
  ':sunrise:': '🌅',
  ':sunrise_over_mountains:': '🌄',
  ':city_sunset:': '🌇',
  ':city_sunrise:': '🌇',
  ':night_with_stars:': '🌃',
  ':milky_way:': '🌌',
  ':bridge_at_night:': '🌉',
  ':foggy:': '🌁',
  ':tent:': '⛺',
  ':camping:': '🏕️',
  ':beach_with_umbrella:': '🏖️',
  ':desert_island:': '🏝️',
  ':desert:': '🏜️',
  ':volcano:': '🌋',
  ':mountain:': '⛰️',
  ':mountain_snow:': '🏔️',
  ':mountain_railway:': '🚞',
  ':european_castle:': '🏰',
  ':japanese_castle:': '🏯',
  ':stadium:': '🏟️',
  ':ferris_wheel:': '🎡',
  ':roller_coaster:': '🎢',
  ':carousel_horse:': '🎠',
  ':water_slide:': '🛝',
  ':tokyo_tower:': '🗼',
  ':statue_of_liberty:': '🗽',
  ':building_construction:': '🏗️',
  ':house:': '🏠',
  ':house_with_garden:': '🏡',
  ':office:': '🏢',
  ':department_store:': '🏬',
  ':factory:': '🏭',
  ':hospital:': '🏥',
  ':bank:': '🏦',
  ':hotel:': '🏨',
  ':love_hotel:': '🏩',
  ':convenience_store:': '🏪',
  ':school:': '🏫',
  ':post_office:': '🏣',
  ':church:': '⛪',
  ':mosque:': '🕌',
  ':synagogue:': '🕍',
  ':kaaba:': '🕋',

  // Objects
  ':phone:': '📱',
  ':calling:': '📲',
  ':computer:': '💻',
  ':keyboard:': '⌨️',
  ':trackball:': '🖲️',
  ':printer:': '🖨️',
  ':desktop_computer:': '🖥️',
  ':battery:': '🔋',
  ':electric_plug:': '🔌',
  ':flashlight:': '🔦',
  ':candle:': '🕯️',
  ':lamp:': '🛋️',
  ':watch:': '⌚',
  ':alarm_clock:': '⏰',
  ':stopwatch:': '⏱️',
  ':timer_clock:': '⏲️',
  ':hourglass_flowing_sand:': '⏳',
  ':hourglass:': '⌛',
  ':satellite:': '🛰️',
  ':compass:': '🧭',
  ':map:': '🗺️',
  ':paperclip:': '📎',
  ':pushpin:': '📌',
  ':round_pushpin:': '📍',
  ':scissors:': '✂️',
  ':straight_ruler:': '📏',
  ':triangular_ruler:': '📐',
  ':black_nib:': '✒️',
  ':pencil2:': '✏️',
  ':pen:': '🖊️',
  ':fountain_pen:': '🖋️',
  ':crayon:': '🖍️',
  ':paintbrush:': '🖌️',
  ':wrench:': '🔧',
  ':nut_and_bolt:': '🔩',
  ':hammer:': '🔨',
  ':hammer_and_wrench:': '🛠️',
  ':pick:': '⛏️',
  ':lock:': '🔒',
  ':unlock:': '🔓',
  ':key:': '🔑',
  ':key2:': '🗝️',
  ':shopping_cart:': '🛒',
  ':trophy:': '🏆',
  ':medal:': '🏅',
  ':guitar:': '🎸',
  ':trumpet:': '🎺',
  ':violin:': '🎻',
  ':drum:': '🥁',
  ':headphones:': '🎧',
  ':microphone:': '🎤',
  ':saxophone:': '🎷',
  ':telescope:': '🔭',
  ':microscope:': '🔬',
  ':camera:': '📷',
  ':camera_with_flash:': '📸',
  ':video_camera:': '📹',
  ':tv:': '📺',
  ':radio:': '📻',
  ':film_projector:': '📽️',
  ':cinema:': '🎦',
  ':notebook:': '📓',
  ':notebook_with_decorative_cover:': '📔',
  ':ledger:': '📒',
  ':books:': '📚',
  ':bookmark:': '🔖',
  ':scroll:': '📜',
  ':memo:': '📝',
  ':newspaper:': '📰',
  ':envelope:': '✉️',
  ':incoming_envelope:': '📨',
  ':email:': '📧',
  ':postbox:': '📮',
  ':package:': '📦',
  ':postal_horn:': '📯',
  ':fax:': '📠',
  ':banknote:': '💵',
  ':dollar:': '💵',
  ':yen:': '💴',
  ':euro:': '💶',
  ':pound:': '💷',
  ':money_with_wings:': '💸',
  ':credit_card:': '💳',
  ':receipt:': '🧾',
  ':moneybag:': '💰',
  ':gem:': '💎',
  ':ring:': '💍',
  ':crown:': '👑',
  ':lipstick:': '💄',
  ':high_heel:': '👠',
  ':dress:': '👗',
  ':bikini:': '👙',
  ':handbag:': '👜',
  ':pouch:': '👝',
  ':shopping_bags:': '🛍️',
  ':gloves:': '🧤',
  ':scarf:': '🧣',
  ':socks:': '🧦',
  ':hat:': '🎩',
  ':sunglasses:': '🕶️',
  ':necktie:': '👔',
  ':tshirt:': '👕',
  ':jeans:': '👖',
  ':boot:': '👢',
  ':kimono:': '👘',
  ':womans_clothes:': '👚',
  ':tophat:': '🎩',
  ':school_satchel:': '🎒',
  ':briefcase:': '💼',
  ':closed_book:': '📕',
  ':book:': '📖',
  ':calendar:': '📅',
  ':mag:': '🔍',
  ':pager:': '📟',
  ':lightning:': '🌩️',
  ':bar_chart:': '📊',
  ':chart_with_upwards_trend:': '📈',
  ':chart_with_downwards_trend:': '📉',
  ':calendar_spiral:': '🗓️',
  ':date:': '📅',
  ':spiral_notepad:': '🗒️',
  ':clipboard:': '📋',
  ':file_folder:': '📁',
  ':open_file_folder:': '📂',
  ':stapler:': '🖇️',
  ':pin:': '📍',
  ':pencil:': '✏️',

  ':knife:': '🔪',
  ':hocho:': '🔪',
  ':dagger:': '🗡️',
  ':axe:': '🪓',
  ':gun:': '🔫',
  ':shield:': '🛡️',
  ':amphora:': '🏺',

  ':hammer_and_pick:': '⚒️',
  ':tools:': '🛠️',
  ':toolbox:': '🧰',
  ':magnet:': '🧲',
  ':chains:': '⛓️',
  ':link:': '🔗',

  ':syringe:': '💉',
  ':pill:': '💊',
  ':health_worker:': '🧑‍⚕️',
  ':brain:': '🧠',
  ':atom_symbol:': '⚛️',
  ':newspaper_roll:': '🗞️',
  ':computer_mouse:': '🖱️',
  ':eject_button:': '⏏️',
  ':compression:': '🗜️',
  ':file_cabinet:': '🗄️',
  ':card_file_box:': '🗃️',
  ':wastebasket:': '🗑️',
  ':floppy_disk:': '💾',
  ':optical_disk:': '💿',
  ':disk:': '💽',
  ':tape:': '📼',
  ':abacus:': '🧮',
  ':magnifying_glass_tilted_left:': '🔍',
  ':magnifying_glass_tilted_right:': '🔎',
  ':prayer_beads:': '📿',
  ':alembic:': '⚗️',
  ':test_tube:': '🧪',
  ':petri_dish:': '🧫',
  ':dna:': '🧬',
  ':safety_pin:': '🧷',
  ':broom:': '🧹',
  ':basket:': '🧺',
  ':roll_of_paper:': '🧻',
  ':soap:': '🧼',
  ':sponge:': '🧽',
  ':fire_extinguisher:': '🧯',
  ':toilet:': '🚽',
  ':shower:': '🚿',
  ':bath:': '🛁',
  ':bed:': '🛏️',
  ':couch_and_lamp:': '🛋️',
  ':toothbrush:': '🪥',
  ':razor:': '🪒',
  ':lotion_bottle:': '🧴',
  ':couch:': '🛋️',
  ':chair:': '🪑',
  ':teacup_without_handle:': '🍵',
  ':stuffed_flatbread:': '🥙',
  ':coffee_pot:': '🫖',
  ':steaming_bowl:': '🍜',
  ':pot_of_food:': '🍲',
  ':bento_box:': '🍱',
  ':hamburger:': '🍔',
  ':salad:': '🥗',
  ':stuffed_pita:': '🥙',
  ':biscuit:': '🍪',
  ':melon_pineapple:': '🍈',
  ':orange:': '🍊',
  ':pear:': '🍐',
  ':mango:': '🥭',
  ':green_apple:': '🍏',
  ':potato:': '🥔',
  ':bread:': '🍞',
  ':croissant:': '🥐',
  ':baguette_bread:': '🥖',
  ':pretzel:': '🥨',
  ':cheese:': '🧀',
  ':egg:': '🍳',
  ':fried_egg:': '🍳',
  ':bacon:': '🥓',
  ':cut_of_meat:': '🥩',
  ':poultry_leg:': '🍗',
  ':meat_on_bone:': '🍖',
  ':pancakes:': '🥞',
  ':rice:': '🍚',
  ':curry_rice:': '🍛',
  ':mortar_board:': '🎓',
  ':backpack:': '🎒',

  ':globe:': '🌍',

  ':open_book:': '📖',
  ':orange_book:': '📙',
  ':green_book:': '📗',
  ':blue_book:': '📘',

  ':notebook_spiral:': '🗒️',
  ':clip_file:': '🗂️',
  ':page_with_curl:': '📃',
  ':hole:': '🕳️',
  ':roll:': '🎲',
  ':tooth:': '🦷',
  ':bone:': '🦴',
  ':hearts:': '♥️',
  ':rainbow:': '🌈',
  ':sun:': '🌞',
  ':moon:': '🌜',
  ':cloud:': '☁️',
  ':cloud_with_rain:': '🌧️',
  ':cloud_with_snow:': '🌨️',
  ':cloud_with_lightning:': '🌩️',
  ':cloud_with_tornado:': '🌪️',
  ':fog:': '🌫️',
  ':umbrella:': '☔',
  ':umbrella_with_rain_drops:': '☔',
  ':snowflake:': '❄️',
  ':comet:': '☄️',
  ':ocean:': '🌊',
  ':ear_of_rice:': '🌾',
  ':four_leaf_clover:': '🍀',
};

export function formatChatText(text: string): string {
  // Convert URLs to clickable links
  const urlRegex =
    /(\b(https?|ftp|file):\/\/[-A-Z0-9+&@#/%?=~_|!:,.;]*[-A-Z0-9+&@#/%=~_|]|www\.[a-zA-Z0-9-]+(\.[a-zA-Z]{2,})+)/gi;
  const linkedText = text.replace(urlRegex, (url) => {
    let href = url;
    if (!/^https?:\/\//i.test(url)) {
      href = `http://${url}`;
    }
    return `<a href="${href}" target="_blank" rel="noopener noreferrer">${url}</a>`;
  });

  const emojiFormattedText = linkedText.replace(
    /:\)|:\(|:D|:P|<3|XD|:o|:thumbsup:|:thumbsdown:|:fire:|:star:|:rocket:/g,
    (match) => {
      return emojiMap[match] || match;
    },
  );

  // Convert newlines to <br> tags
  const newLineFormattedText = emojiFormattedText.replace(/\n/g, '<br>');

  // Highlight mentions
  const mentionRegex = /@([a-zA-Z0-9_]+)/g;
  const mentionFormattedText = newLineFormattedText.replace(
    mentionRegex,
    '<span class="mention">@$1</span>',
  );

  // emoji regex
  const emojiRegex = /^(?:[\p{Emoji}\u200d\ufe0f]+)$/u;
  const emojiText = mentionFormattedText.replace(emojiRegex, (match) => {
    return `<span class="chat-message-emoji">${match}</span>`;
  });

  // Convert hashtags to links
  const hashtagRegex = /#(\w+)/g;
  const hashtagFormattedText = emojiText.replace(
    hashtagRegex,
    '<a href="/hashtag/$1" class="hashtag">#$1</a>',
  );

  return hashtagFormattedText;
}
