/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthLoginImport } from './routes/auth/login'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ChatIndexLazyImport = createFileRoute('/chat/')()
const AuthResetPinLazyImport = createFileRoute('/auth/reset-pin')()
const AuthJoinLazyImport = createFileRoute('/auth/join')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ChatIndexLazyRoute = ChatIndexLazyImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/chat/index.lazy').then((d) => d.Route))

const AuthResetPinLazyRoute = AuthResetPinLazyImport.update({
  id: '/auth/reset-pin',
  path: '/auth/reset-pin',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/auth/reset-pin.lazy').then((d) => d.Route),
)

const AuthJoinLazyRoute = AuthJoinLazyImport.update({
  id: '/auth/join',
  path: '/auth/join',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/join.lazy').then((d) => d.Route))

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/join': {
      id: '/auth/join'
      path: '/auth/join'
      fullPath: '/auth/join'
      preLoaderRoute: typeof AuthJoinLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/reset-pin': {
      id: '/auth/reset-pin'
      path: '/auth/reset-pin'
      fullPath: '/auth/reset-pin'
      preLoaderRoute: typeof AuthResetPinLazyImport
      parentRoute: typeof rootRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/join': typeof AuthJoinLazyRoute
  '/auth/reset-pin': typeof AuthResetPinLazyRoute
  '/chat': typeof ChatIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/join': typeof AuthJoinLazyRoute
  '/auth/reset-pin': typeof AuthResetPinLazyRoute
  '/chat': typeof ChatIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/join': typeof AuthJoinLazyRoute
  '/auth/reset-pin': typeof AuthResetPinLazyRoute
  '/chat/': typeof ChatIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/login' | '/auth/join' | '/auth/reset-pin' | '/chat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/login' | '/auth/join' | '/auth/reset-pin' | '/chat'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/join'
    | '/auth/reset-pin'
    | '/chat/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthJoinLazyRoute: typeof AuthJoinLazyRoute
  AuthResetPinLazyRoute: typeof AuthResetPinLazyRoute
  ChatIndexLazyRoute: typeof ChatIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthJoinLazyRoute: AuthJoinLazyRoute,
  AuthResetPinLazyRoute: AuthResetPinLazyRoute,
  ChatIndexLazyRoute: ChatIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/login",
        "/auth/join",
        "/auth/reset-pin",
        "/chat/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/join": {
      "filePath": "auth/join.lazy.tsx"
    },
    "/auth/reset-pin": {
      "filePath": "auth/reset-pin.lazy.tsx"
    },
    "/chat/": {
      "filePath": "chat/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
