apiVersion: v1
kind: Service
metadata:
  name: blackout-chat-service

spec:
  type: LoadBalancer
  selector:
    app: blackout-chat-pod
  ports:
  - port: 4001
    targetPort: 4001
    nodePort: 30001

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  type: ClusterIP
  selector:
    app: mongodb-pod
  ports:
  - port: 27017
    targetPort: 27017

---

apiVersion: v1
kind: Secret
metadata:
  name: blackout-chat-secret
type: Opaque
data:
  mongodb-username: YWRtaW4=
  mongodb-password: YWRtaW4=


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  database-host: mongodb-service
  database-name: blackout-chat
