// Generated by CodiumAI

import { slugify } from '../slug';

describe('utils/slugify', () => {
  // Should return a string with no spaces and hyphens instead
  it('should return a string with no spaces and hyphens instead when input has spaces', () => {
    const input = 'hello world';
    const expected = 'hello-world';
    const result = slugify(input);
    expect(result).toEqual(expected);
  });

  // Should return an empty string when input is null or undefined
  it('should return an empty string when input is null', () => {
    const input = null;
    const expected = '';
    const result = slugify(input);
    expect(result).toEqual(expected);
  });

  // Should return an empty string when input is null or undefined
  it('should return an empty string when input is undefined', () => {
    const input = undefined;
    const expected = '';
    const result = slugify(input);
    expect(result).toEqual(expected);
  });

  // Should return an empty string when input is an empty string
  it('should return an empty string when input is an empty string', () => {
    const input = '';
    const expected = '';
    const result = slugify(input);
    expect(result).toEqual(expected);
  });

  // Should handle input with leading and trailing spaces
  it('should handle input with leading and trailing spaces', () => {
    const input = '  hello world  ';
    const expected = 'hello-world';
    const result = slugify(input);
    expect(result).toEqual(expected);
  });

  // Should handle input with special characters other than hyphens
  it('should handle input with special characters other than hyphens', () => {
    const input = 'hello!@#$%^&*()world';
    const expected = 'hello!@#$%^&*()world';
    const result = slugify(input);
    expect(result).toEqual(expected);
  });
});
