name: Continuous Deployment to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Continuous Deployment to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          debug: true
          script: |
            cd ./apps/blackout-chat
            git clean -f
            git pull origin main --ff-only
            docker compose down
            docker compose up -d --build
